name: Scraper de Voos

on:
  schedule:
    # Rodar de hora em hora, minuto 0
    - cron: "0 * * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar scraper
        run: |
          source venv/bin/activate
          python scraper/scraper.py