name: Flight Scraper

on:
  schedule:
    # Roda todo dia, de hora em hora, das 16:00 até 23:00
    - cron: "0 16-23 * * *"
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          source venv/bin/activate
          python scraper/scraper.py